BEGIN;
SET NAMES utf8mb4;

DELETE FROM `prompt_templates`
WHERE `id` IN (
    '1', '2', '3', '4', '5', '6',
    'system_actor_image', 'system_character_image', 'system_prop_image', 'system_costume_image',
    'system_scene_image_front', 'system_scene_image_other',
    'system_frame_head_image', 'system_frame_key_image', 'system_frame_tail_image',
    'system_video_prompt'
);

INSERT INTO `prompt_templates`
    (`id`, `category`, `name`, `preview`, `content`, `variables`, `variable_defaults`, `version`, `created_at`, `updated_at`, `is_system`, `is_default`)
VALUES
    ('system_actor_image', 'actor_image', '演员身份设定图', '锁定真人演员的面部、体态与服装身份，适合建立后续一致性参考。', '生成用于 AI 短剧制作的演员身份设定图。\n演员：{{ name }}。人物设定：{{ description }}。标签：{{ tags }}。\n视角：{{ view_angle }}。{{ reference_instruction }}\n画面用途：身份与外观一致性参考，不表现剧情事件。\n构图：{{ framing_instruction }}\n细节：{{ visible_detail_instruction }}\n背景：{{ background_instruction }}\n光线：{{ lighting_instruction }}\n项目风格：{{ visual_style }}，{{ style }}。\n避免：{{ negative_prompt }}', '["name", "description", "tags", "view_angle", "reference_instruction", "framing_instruction", "visible_detail_instruction", "background_instruction", "lighting_instruction", "visual_style", "style", "negative_prompt"]', '{"framing_instruction":"单人全身或四分之三身，人物居中，姿态自然，无遮挡。","visible_detail_instruction":"清楚呈现五官、发型、身材比例、服装材质与识别特征。","background_instruction":"纯净无缝棚拍背景，不出现剧情场景、其他人物或无关道具。","lighting_instruction":"柔和均匀棚拍光，肤色准确，面部和衣料纹理清晰。","negative_prompt":"文字、字幕、标志、水印、多人、遮挡、模糊、肢体畸形、重复肢体、过度磨皮"}', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_character_image', 'character_image', '角色一致性设定图', '融合演员、服装与角色设定，形成可供分镜持续引用的角色基准图。', '生成用于 AI 短剧连续镜头的角色一致性设定图。\n角色：{{ name }}。角色设定：{{ description }}。\n视角：{{ view_angle }}。{{ reference_instruction }}\n必须保持参考素材中的身份、脸型、发型、年龄感、体态与服装主色一致；允许按当前视角自然补全，不机械复制姿势。\n构图：{{ framing_instruction }}\n背景：{{ background_instruction }}\n光线：{{ lighting_instruction }}\n项目风格：{{ visual_style }}，{{ style }}。\n避免：{{ negative_prompt }}', '["name", "description", "view_angle", "reference_instruction", "framing_instruction", "background_instruction", "lighting_instruction", "visual_style", "style", "negative_prompt"]', '{"framing_instruction":"单人全身角色设计展示，人物完整、无遮挡、比例自然。","background_instruction":"纯净中性背景，不表现剧情事件。","lighting_instruction":"均匀柔光，面部和服装结构清晰。","negative_prompt":"身份漂移、换脸、服装换色、年龄变化、多人、文字、水印、模糊、畸形"}', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_prop_image', 'prop_image', '道具标准展示图', '明确道具形状、材质、尺度和可识别细节，供场景与镜头引用。', '生成用于 AI 短剧资产库的道具标准展示图。\n道具：{{ name }}。设定：{{ description }}。标签：{{ tags }}。\n视角：{{ view_angle }}。{{ reference_instruction }}\n完整展示外形、材质、颜色、磨损程度、尺寸尺度和关键识别细节。\n构图：{{ framing_instruction }}\n背景：{{ background_instruction }}\n光线：{{ lighting_instruction }}\n项目风格：{{ visual_style }}，{{ style }}。\n避免：{{ negative_prompt }}', '["name", "description", "tags", "view_angle", "reference_instruction", "framing_instruction", "background_instruction", "lighting_instruction", "visual_style", "style", "negative_prompt"]', '{"framing_instruction":"单个道具居中完整展示，比例清楚，无裁切和遮挡。","background_instruction":"纯净中性棚拍背景，不加入使用者和剧情场景。","lighting_instruction":"产品摄影布光，材质、边缘和结构清晰。","negative_prompt":"人物、手持、复杂场景、重复物体、文字、标志、水印、模糊、形变"}', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_costume_image', 'costume_image', '服装造型设定图', '锁定服装轮廓、材质、配色和时代特征，供角色一致性使用。', '生成用于 AI 短剧资产库的服装造型设定图。\n服装：{{ name }}。设定：{{ description }}。标签：{{ tags }}。\n视角：{{ view_angle }}。{{ reference_instruction }}\n清楚表现整体轮廓、版型、材质、配色、纹样、配饰和时代特征。\n构图：{{ framing_instruction }}\n背景：{{ background_instruction }}\n光线：{{ lighting_instruction }}\n项目风格：{{ visual_style }}，{{ style }}。\n避免：{{ negative_prompt }}', '["name", "description", "tags", "view_angle", "reference_instruction", "framing_instruction", "background_instruction", "lighting_instruction", "visual_style", "style", "negative_prompt"]', '{"framing_instruction":"服装完整展示，正交视角，结构无遮挡，便于后续角色引用。","background_instruction":"纯净中性棚拍背景，不加入剧情场景。","lighting_instruction":"均匀柔光，面料纹理与配色准确。","negative_prompt":"服装换色、结构缺失、无关配饰、多人、文字、水印、模糊、畸形"}', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_scene_image_front', 'scene_image_front', '场景空间基准图', '建立空间布局、光线、时代和主要视觉锚点，供分镜连续使用。', '生成用于 AI 短剧制作的场景空间基准图。\n场景：{{ name }}。场景设定：{{ description }}。标签：{{ tags }}。\n观察视角：{{ view_angle }}。{{ reference_instruction }}\n清楚建立前景、中景、背景、出入口、主要家具或地标的相对位置；画面是空间资料图，不发生剧情动作。\n项目风格：{{ visual_style }}，{{ style }}。\n构图：{{ framing_instruction }}\n光线：{{ lighting_instruction }}\n避免：{{ negative_prompt }}', '["name", "description", "tags", "view_angle", "reference_instruction", "visual_style", "style", "framing_instruction", "lighting_instruction", "negative_prompt"]', '{"framing_instruction":"广角平视建立镜头，透视自然，空间关系清楚，保留可供人物活动的区域。","lighting_instruction":"符合场景时间与天气的主光方向，曝光自然，材质可辨。","negative_prompt":"人物表演、剧情事件、空间结构冲突、鱼眼畸变、文字、标志、水印、过曝、欠曝"}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_scene_image_other', 'scene_image_other', '场景补充视角图', '从侧面或背面补全空间关系，并继承场景基准图。', '基于参考图生成同一场景的补充视角。\n场景：{{ name }}。场景设定：{{ description }}。\n目标视角：{{ view_angle }}。{{ reference_instruction }}\n保持建筑结构、陈设、材质、色彩、时间和主光方向一致，只改变观察位置；补全参考图不可见区域时遵循既有空间逻辑。\n项目风格：{{ visual_style }}，{{ style }}。\n避免：{{ negative_prompt }}', '["name", "description", "view_angle", "reference_instruction", "visual_style", "style", "negative_prompt"]', '{"negative_prompt":"改变场景身份、移动固定陈设、时间突变、光向冲突、人物表演、文字、标志、水印、透视畸变"}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_frame_head_image', 'frame_head_image', '首帧建立与触发', '首帧负责承接上一镜头、建立空间，并停在动作触发前或刚触发的可运动状态。', '生成 AI 短剧单镜头的首帧图片。\n主画面：{{ prompt }}\n帧职责：建立人物站位、空间轴线、视线和动作起点；若有上一镜头则自然承接，不提前完成本镜头动作。\n导演指令：{{ director_command_summary }}\n连续性：{{ continuity_guidance }}\n当前帧：{{ frame_specific_guidance }}\n构图锚点：{{ composition_anchor }}\n朝向与视线：{{ screen_direction_guidance }}\n画面应是一个清晰、可继续运动的瞬间；保持关联角色、服装、场景与道具身份一致。', '["prompt", "director_command_summary", "continuity_guidance", "frame_specific_guidance", "composition_anchor", "screen_direction_guidance"]', '{}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_frame_key_image', 'frame_key_image', '关键帧动作峰值', '关键帧聚焦本镜头最有信息量的动作峰值或情绪转折。', '生成 AI 短剧单镜头的关键帧图片。\n主画面：{{ prompt }}\n帧职责：选择最能表达因果、动作峰值或情绪转折的瞬间，动作姿态清楚，不与首帧或尾帧重复。\n导演指令：{{ director_command_summary }}\n连续性：{{ continuity_guidance }}\n当前帧：{{ frame_specific_guidance }}\n构图锚点：{{ composition_anchor }}\n朝向与视线：{{ screen_direction_guidance }}\n保持关联角色、服装、场景与道具身份一致，空间和屏幕方向可与相邻帧连续。', '["prompt", "director_command_summary", "continuity_guidance", "frame_specific_guidance", "composition_anchor", "screen_direction_guidance"]', '{}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_frame_tail_image', 'frame_tail_image', '尾帧收束与衔接', '尾帧形成动作或情绪落点，并为下一镜头保留连续入口。', '生成 AI 短剧单镜头的尾帧图片。\n主画面：{{ prompt }}\n帧职责：呈现本镜头动作结果和情绪余韵；若有下一镜头，保留可自然衔接的视线、姿态、道具状态或运动方向。\n导演指令：{{ director_command_summary }}\n连续性：{{ continuity_guidance }}\n当前帧：{{ frame_specific_guidance }}\n构图锚点：{{ composition_anchor }}\n朝向与视线：{{ screen_direction_guidance }}\n保持关联角色、服装、场景与道具身份一致，不无故跳轴或重置状态。', '["prompt", "director_command_summary", "continuity_guidance", "frame_specific_guidance", "composition_anchor", "screen_direction_guidance"]', '{}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    ('system_video_prompt', 'video_prompt', '短剧单镜头视频生成', '把镜头事实、动作节拍、运镜和连续性编译成可直接提交的视频提示词。', '生成一个 AI 短剧单镜头。\n镜头：{{ shot_title }}。剧本内容：{{ script_excerpt }}\n主体与场景：角色 {{ character_names }}；场景 {{ scene_name }}；道具 {{ prop_names }}；服装 {{ costume_names }}。\n动作按时间顺序发生：{{ action_beats_text }}。动作应具有起因、过程和落点，不在同一时刻堆叠互相冲突的动作。\n镜头语言：景别 {{ camera_shot }}，机位 {{ angle }}，运镜 {{ movement }}，时长 {{ duration }} 秒。运镜只服务主体动作，避免无动机晃动。\n对白：{{ dialogue_summary }}。对白存在时保持说话者、口型、语气和对视关系自然；没有明确对白时不要擅自增加台词。\n上一镜头承接：{{ previous_shot_summary }}\n下一镜头目标：{{ next_shot_goal }}\n连续性：{{ continuity_guidance }}\n构图锚点：{{ composition_anchor }}\n朝向与视线：{{ screen_direction_guidance }}\n氛围与风格：{{ atmosphere }}；{{ visual_style }}；{{ style }}。\n避免：{{ negative_prompt }}', '["shot_title", "script_excerpt", "character_names", "scene_name", "prop_names", "costume_names", "action_beats_text", "camera_shot", "angle", "movement", "duration", "dialogue_summary", "previous_shot_summary", "next_shot_goal", "continuity_guidance", "composition_anchor", "screen_direction_guidance", "atmosphere", "visual_style", "style", "negative_prompt"]', '{}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

COMMIT;
