/** Native controls fixtures do not connect to Jimeng or use an account. */
import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {modelOption,observeJimengNative,prepareJimengImageDraft,selectJimengModel} from './jimeng-controls.mjs';
/** Fulfil the official entry locally, keeping all tests below the submit boundary. */
async function fixture(html,run){const b=await chromium.launch({channel:'msedge',headless:true});try{const c=await b.newContext({serviceWorkers:'block'});await c.route('**/*',r=>r.fulfill({contentType:'text/html;charset=utf-8',body:html}));await run(await c.newPage())}finally{await b.close()}}
const html='<div role="combobox">图片生成</div><div role="combobox" id="model">图片 3.0</div><div role="option" onclick="document.getElementById(\'model\').innerText=\'图片 3.0\'">图片 3.0<br>影视质感</div><div role="textbox" contenteditable="true"></div><button onclick="window.sent=true">生成</button>';
test('option parsing distinguishes promotional copy, disabled and VIP',()=>{assert.equal(modelOption('图片 3.0\n文字更准').name,'图片 3.0');assert.equal(modelOption('即梦 Seedance 1.0','lv-select-option-wrapper-disabled').disabled,true);assert.equal(modelOption('即梦 Seedance 2.0 VIP\n会员专属').membership_notice,true)});
test('native image preparation keeps exact model and prompt without submitting',()=>fixture(html,async p=>{const result=await prepareJimengImageDraft(p,{requested_model:'图片 3.0',prompt:'一支铅笔',reference_file_ids:[]});assert.equal(result.submitted,false);assert.equal(await p.getByRole('textbox').innerText(),'一支铅笔');assert.equal(await p.evaluate(()=>window.sent||false),false)}));
test('disabled model and ambiguous matches fail before any generation',()=>fixture(html.replace('role="option"','role="option" class="lv-select-option-wrapper-disabled"'),async p=>{await assert.rejects(selectJimengModel(p,'image','图片 3.0'),/禁用/);assert.equal(await p.evaluate(()=>window.sent||false),false)}));
test('model menu is evidence only, not automatic support or free entitlement',()=>fixture(html,async p=>{const observed=await observeJimengNative(p,'image');assert.equal(observed.models[0].name,'图片 3.0');assert.equal(observed.automatic_supported,false);assert.equal(await p.evaluate(()=>window.sent||false),false)}));
